name: test_workflow_on_events
on:
  # push:
  #   branches:
  #     - main
  #     - dev
  # pull_request:
  #   types:
  #     created
  #   branches:
  #     - main
  workflow_dispatch:
  # environment: dev ---> it can not be used under events
jobs:

  init:
    name: init-job
    runs-on: ubuntu-latest
    # environment: dev

    steps:
      - name: get-code
        uses: "actions/checkout@v2"
      - name: code-status
        run: echo "code was downloaded"
      - name: install terraform
        uses: "hashicorp/setup-terraform@v3"
        with:
          terraform_version: latest
          terraform_wrapper: false
      - name: init
        run: terraform init
      
      
  validate:
    name: validate
    runs-on: windows-latest
    needs: init
    # the continue-on-error will use to make skip errors and make run next jobs and steps
    # it can be used steps and jobs level
    continue-on-error: true
    

    steps:
      - name: get-code
        uses: "actions/checkout@v2"
      - name: code-status
        run: echo "code was downloaded"
      - name: terraform-validate
        id: validate
        run: terraform vlaidate
        continue-on-error: false
  plan:
    name: plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: get-code
        uses: "actions/checkout@v2"
      - name: plan
        run: terrform plan
        id: plan
    
    
        
