name: matrix_workflow
on: push

jobs:
  
  init-job:
    strategy:
      matrix:
        opertaing-systems: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: get_code
        uses: "actions/checkout@v2"
        
