name: matrix_workflow
on: [push, workflow_dispatch]

jobs:
  
  init-job:
    strategy:
      matrix:
        opertaing-system: [ubuntu-latest, windows-latest]
    
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: "actions/checkout@v2"
      - name: code-status
        run: echo "code was downloaded"
        
