name: resuable_workflow
on: workflow_call
jobs:
  init-job:
    name: init
    runs-on: ubuntu-latest
    steps:
    - name: get-code
      run: echo "got the code"
    - name: name
      run: echo "this was run and print from another workflow which is triggered"
